# Name your project!
name: 'dbt_finance_economics_events'
version: '1.0.0'

# Which profile to use
profile: 'dbt_finance_economics_events'

# File paths for dbt resources
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where to clean with `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations by folder
models:
  dbt_finance_economics_events:
    staging:
      +schema: dbt_finance_economics_events_stg
      +materialized: incremental
    intermediate:
      +schema: dbt_finance_economics_events_int
      +materialized: incremental
    mart:
      +schema: dbt_finance_economics_events_mrt
      +materialized: incremental



