version: 2

sources:
  - name: finance_economics_events_stg
    tables:
      - name: crime_data
      - name: gdp
      - name: mortality_and_natality
      - name: state_energy_consumption
      - name: state_level_unemployment_data
      - name: state_exp_data_1991_2024
      - name: state_exp_data_1991_2024_key
      - name: states_cities
      - name: us_geocode

models:
  - name: stg_crime_data
    columns:
      - name: state
        tests: [not_null]
      - name: year
        tests: [not_null]

  - name: stg_gdp
    columns:
      - name: state
        tests: [not_null]
      - name: year
        tests: [not_null]
      - name: category
        tests: [not_null]

  - name: stg_mortality_and_natality
    columns:
      - name: state
        tests: [not_null]
      - name: year
        tests: [not_null]
      - name: month
        tests: [not_null]
      - name: indicator
        tests: [not_null]

  - name: stg_state_energy_consumption
    columns:
      - name: state
        tests: [not_null]
      - name: year
        tests: [not_null]
      - name: sector
        tests: [not_null]

  - name: stg_state_level_unemployment_data
    columns:
      - name: fips_code
        tests: [not_null]
      - name: year
        tests: [not_null]
      - name: employment
        tests: [not_null]
      - name: unemployment
        tests: [not_null]

  - name: stg_state_exp_data_1991_2024
    columns:
      - name: state
        tests: [not_null]
      - name: year
        tests: [not_null]

  - name: stg_state_exp_data_1991_2024_key
    columns:
      - name: the_abbreviation
        tests: [not_null]
      - name: the_full_name
        tests: [not_null]

  - name: stg_states_cities
    columns:
      - name: state_id
        tests: [not_null]
      - name: cities
        tests: [not_null]
      - name: state_name
        tests: [not_null]

  - name: stg_us_geocode
    columns:
      - name: state_abbreviation
        tests: [not_null]
      - name: state_full_name
        tests: [not_null]
